export const CHANGE_LOGIN = 'changeLogin'
export const CHAGNE_TIPS = 'changTips'
export const CHAGNE_SHOWTIPS = 'changeIsTips'
export const CHANGE_PAGES = 'changePages'
export const CHANGE_SHOWSELECT = 'changeIsSelect'
